# Generated by Django 4.1.7 on 2023-05-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
