# Generated by Django 4.1.7 on 2023-05-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
