# Generated by Django 4.1.7 on 2023-04-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='message_is_read',
            field=models.BooleanField(default=False),
        ),
    ]
